# Generated by Django 5.0.2 on 2024-02-16 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('generic', '0005_genericpage_authors'),
    ]

    operations = [
        migrations.RenameField(
            model_name='genericpage',
            old_name='authors',
            new_name='author',
        ),
    ]
