# Generated by Django 5.0.2 on 2024-02-16 07:53

from django.db import migrations


def remove_default_value_from_body(apps, schema_editor):
    GenericPage = apps.get_model('generic', 'GenericPage')
    GenericPage.objects.update(body=None)


class Migration(migrations.Migration):
    dependencies = [
        ('generic', '0007_genericpage_body'),
    ]

    operations = [
        migrations.RunPython(remove_default_value_from_body),
    ]